restart: unless-stopped
volumes:
  - ./loki/loki-config.yml:/etc/loki/local-config.yml
  - loki_data:/loki
ports: 
- "3100:3100"
command: -config.file=/etc/loki/local-config.yml
networks:
- monitoring

promtail: 
  image: grafana/promtail:latest
  container_name: promtail
  restart: unless-stopped
  volumes:
    - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    - /var/log:/var/log
  command: -config.file=/etc/promtail/config.yml
  networks:
    - monitoring
  depends_on:
    - loki
  
node-exporter:
  image: prom/node-exporter:latest
  container_name: node-exporter
  restart: unless-stopped
  volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
  command: 
    - '--path.procfs=/host/proc'
    - '--path.rootfs =/' 
